net: Unetv2
load_checkpoint: D:\weights\checkpoint8
dataset: D:\Datasets\GID15\gid-15\GID\Validation
num_classes: 15
patch_size: 224
device: gpu
verbose: True
confusion_matrix: 'confusion.png'
priors: 'priors.png'
ignore_background: True