net: Ensemble
#load_checkpoint: D:\weights\checkpoint20
dataset: D:\Datasets\GID15\gid-15\GID\Validation
num_classes: 15
patch_size: 224
device: gpu
verbose: True
confusion_matrix: 'test.png'
priors: 'priors.png'
ensemble_config: 'test.yaml'