net: SegformerMod
load_checkpoint: /homes/nmorelli/checkpoints/segformer/checkpoint63
#load_checkpoint: /home/nicola/Desktop/checkpoints/deeplabv3/resnet101/checkpoint64
dataset: /work/cvcs2024/MSseg/Validation
#dataset: /home/nicola/CVCS/dataset/GID15/Test
device: gpu
#device: cpu
num_classes: 15
patch_size: 224
verbose: True
confusion_matrix: '/homes/nmorelli/output/confusion.png'
priors: '/homes/nmorelli/output/priors.png'
ignore_background: True