net: Unetv2
load_checkpoint: D:\weights\test\balanced\UnetNoBackWeighted\checkpoint50
dataset: D:\Datasets\GID15\gid-15\GID\Validation
num_classes: 15
patch_size: 224
device: gpu
verbose: True
confusion_matrix: 'confusion.png'
priors: 'priors.png'
ignore_background: True

load_context: False
load_color_mask: False
ensemble_config: "test.yaml"