net: Resnet101
load_checkpoint: /homes/nmorelli/checkpoints/deeplabv3/resnet101/checkpoint64
#load_checkpoint: /home/nicola/Desktop/checkpoints/deeplabv3/resnet101/checkpoint64
dataset: /work/cvcs2024/MSseg/Test
#dataset: /home/nicola/CVCS/dataset/GID15/Test
num_classes: 15
patch_size: 224
device: cpu
verbose: True
confusion_matrix: '/homes/nmorelli/output/confusion.png'
priors: '/homes/nmorelli/output/priors.png'
ignore_background: True