train: D:\Datasets\GID15_test\Train
validation: D:\Datasets\GID15_test\Validation
test: D:\Datasets\GID15_test\Test
device: gpu
checkpoint_directory: D:\weights\test # directory to save checkpoints in
load_checkpoint: D:\weights\checkpoint8
epochs: 40
patch_size: 224
chunk_size: 5
freq: 1
verbose: True
batch_size: 4
precision_evaluation_freq: 1
net: Unetv2
opt: SGD1
loss: CEL
num_classes: 15
patch_size: 224