#-------------DEBUGGING-----------
debug: False
debug_plot: False
verbose: True

#-------------DIRECTORIES------------
train: D:\Datasets\GID15_urban\GID15\Train
validation: D:\Datasets\GID15_urban\GID15\Validation
test: D:\Datasets\GID15_urban\GID15\Test
checkpoint_directory: D:\weights\test\urban # directory to save checkpoints in
load_checkpoint: D:\weights\test\urban\checkpoint20
#--------DEVICE--------------
device: gpu

#----NET AND CONTEXT----------
net: Unetv2
load_context: False

#-------DATA LOADING----------
epochs: 40
chunk_size: 20
patch_size: 224
batch_size: 4
augmentation: False
#random_tps: [[512, 0.5],[1024, 0.5]]

# ------LOSS AND OPTIMIZATION----------
loss: CEL
opt: SGD1
ignore_background: False

#-------ALMOST NEVER TOUCH THESE--------
freq: 1
precision_evaluation_freq: 1
num_classes: 15
load_color_mask: False