train: D:\Datasets\GID15\gid-15\GID\Train
validation: D:\Datasets\GID15\gid-15\GID\Validation
test: D:\Datasets\GID15\gid-15\GID\Test
device: gpu
checkpoint_directory: D:\weights\test # directory to save checkpoints in
net: Unetv2
epochs: 20
chunk_size: 10
patch_size: 224
batch_size: 4
verbose: True

freq: 1
precision_evaluation_freq: 1
opt: SGD1
loss: CEL
num_classes: 15