debug: True
debug_plot: False
random_tps: [ [ 511, 0.25 ] ]

train: /home/nicola/CVCS/dataset/GID15/Train/Patches_512x512
validation: /home/nicola/CVCS/dataset/GID15/Validation
test: /home/nicola/CVCS/dataset/GID15/Test
checkpoint_directory: /home/nicola/Desktop/checkpoints # directory to save checkpoints in
#load_checkpoint: /home/nicola/Desktop/checkpoints/segformer/checkpoint64

device: cpu
augmentation: True
net: MobileNet
backbone: resnet18
epochs: 16
chunk_size: 168
patch_size: 224
batch_size: 4
verbose: True

loss: CEL
opt: ADAM2
freq: 1
precision_evaluation_freq: 4
num_classes: 15
ignore_background: True
load_context: False
load_color_mask: False