debug: True
debug_plot: False
random_tps: [[512, 0.5],[1024, 0.5]]

train: /home/nicola/CVCS/dataset/GID15/Train
validation: /home/nicola/CVCS/dataset/GID15/Validation
test: /home/nicola/CVCS/dataset/GID15/Test
checkpoint_directory: /home/nicola/Desktop/checkpoints # directory to save checkpoints in

device: cpu
augmentation: False
ignore_background: True
net: SegformerMod
epochs: 12
chunk_size: 1
patch_size: 224
batch_size: 4
verbose: True

loss: CEL
opt: ADAM2
freq: 1
precision_evaluation_freq: 4
num_classes: 15