train: D:\Datasets\GID15_test\Train
validation: D:\Datasets\GID15_test\Validation
test: D:\Datasets\GID15_test\Test
device: gpu
checkpoint_directory: D:\weights\test # directory to save checkpoints in
#load_checkpoint: D:\weights\checkpoint8
net: Unetv2
epochs: 1
chunk_size: 2
patch_size: 224
batch_size: 4
verbose: True

freq: 1
precision_evaluation_freq: 1
opt: SGD1
loss: CEL
num_classes: 15

#random_tps: [256, 512]
#debug: True