train: D:\Datasets\GID15_test\Train
validation: D:\Datasets\GID15_test\Validation
test: D:\Datasets\GID15_test\Test
device: gpu
checkpoint_directory: D:\weights\test # directory to save checkpoints in
# uncomment load_checkpoint if you want to load a checkpoint
#load_checkpoint: D:\weights\small_unet\checkpoint18
epochs: 10 # number of epochs.
# warning: if you ended at epoch 10 at last checkpoint and you want to train for 10 more epochs,
# then set this value to 20 (10 + 10)
chunk_size: 5
freq: 1 # checkpoint saving frequency. If set to 2, a checkpoint will be saved every 2 epochs.
verbose: True # show progress bar during epochs. Keep false if you train on remote server
batch_size: 4 # this parameter will be overwritten if a checkpoint is loaded
precision_evaluation_freq: 1 # if set to 2, it will evaluate model precision once every 2 epochs

net: Unetv2
# Avaliable models:
# TSwin: Tiny swin transformer backbone (hugging face) + unet decoder with residuals
# BSwin: Base swin transformer backbone (hugging face) + unet decoder with residuals
# Unet: Classic unet network (2015 medical segmentation paper)
# Unetv2: Unet with Transpose Convolution in decoding path

opt: SGD1
loss: CEL
# DEL: DiceEntropyLoss
# CEL: CrossEntropyLoss
# DL: DiceLoss
num_classes: 15