debug: True
debug_plot: False

train: /work/cvcs2024/MSseg/Train
validation: /work/cvcs2024/MSseg/Validation
test: /work/cvcs2024/MSseg/Test

device: gpu
checkpoint_directory:  /homes/nmorelli/checkpoints/segformer
net: SegformerMod
epochs: 12
chunk_size: 10
patch_size: 224
batch_size: 16
verbose: True

freq: 1
precision_evaluation_freq: 4
opt: ADAM2
loss: CEL
num_classes: 15
ignore_background: True
parallel: True