debug: True
debug_plot: False
random_tps: [ [ 511, 0.25 ] ]

train: /work/cvcs2024/MSseg/Patches_512x512
validation: /work/cvcs2024/MSseg/Validation
test: /work/cvcs2024/MSseg/Test
checkpoint_directory: /homes/nmorelli/checkpoints/deeplabv3/mobile_net
#load_checkpoint: /homes/nmorelli/checkpoints/segformer/checkpoint44

device: gpu
augmentation: True
net: MobileNet
epochs: 64
chunk_size: 168
patch_size: 224
batch_size: 32
verbose: True

loss: CEL
opt: ADAM2
freq: 1
precision_evaluation_freq: 4
num_classes: 15
ignore_background: True
load_context: False
load_color_mask: False