debug: True
debug_plot: False
random_tps: [[512, 0.5],[1024, 0.5]]

train: /work/cvcs2024/MSseg/Train
validation: /work/cvcs2024/MSseg/Validation
test: /work/cvcs2024/MSseg/Test
checkpoint_directory:  /homes/nmorelli/checkpoints/segformer

device: gpu
net: SegformerMod
epochs: 12
chunk_size: 5
patch_size: 224
batch_size: 16
verbose: True

loss: CEL
opt: ADAM2
freq: 1
precision_evaluation_freq: 4
num_classes: 15
ignore_background: True
parallel: True