dataset: D:\Datasets\GID15\gid-15\GID\Validation
device: gpu

net: Unetv2
load_checkpoint: D:\weights\test\balanced\UnetNoBack\checkpoint50
patch_size: 224
border_correction: 256

range: [0,960]

mask_only: True
out_image: "map.png"
ensemble_config: 'test.yaml'
num_classes: 15